import Event from 'SpectaclesInteractionKit.lspkg/Utils/Event'
import {FlexLayout} from 'SpectaclesUIKit.lspkg/Scripts/Components/Layout2D/Flex/FlexLayout'
import {FlexItem} from 'SpectaclesUIKit.lspkg/Scripts/Components/Layout2D/Flex/FlexItem'
import {FlexAlign,FlexAlignSelf,FlexDirection,FlexJustify} from 'SpectaclesUIKit.lspkg/Scripts/Components/Layout2D/Flex/FlexTypes'
import {BackPlate} from 'SpectaclesUIKit.lspkg/Scripts/BackPlate'
import {Button} from 'SpectaclesUIKit.lspkg/Scripts/Components/Button/Button'
import {ElementContent} from 'SpectaclesUIKit.lspkg/Scripts/Components/Content/ElementContent'
import {RoundedRectangle} from 'SpectaclesUIKit.lspkg/Scripts/Visuals/RoundedRectangle/RoundedRectangle'
import {OrbitTask,TaskState} from './FocusOrbitModel'
import {FocusProfile} from './FocusOrbitAdaptive'
import {SpatialTaskManipulationController,SpatialTaskManipulationHost} from './SpatialTaskManipulationController'

type TextRole='Title2'|'HeadlineXL'|'Headline1'|'Subheadline'|'Button'|'Body'|'Caption'|'Task'|'Meta'
type OnboardingState='GET_STARTED'|'INSTRUCTIONS'|'WORKSPACE'
export type RecoveryAction='START_BREAK'|'CONTINUE'|'END_BREAK'
const ONBOARDING_KEY='focusOrbit.hasCompletedOnboarding.v1'
const SCALE:Record<TextRole,{size:number,weight:number}>={Title2:{size:82,weight:700},HeadlineXL:{size:60,weight:700},Headline1:{size:48,weight:700},Subheadline:{size:41,weight:600},Button:{size:38,weight:500},Body:{size:36,weight:400},Caption:{size:32,weight:500},Task:{size:33,weight:500},Meta:{size:29,weight:500}}
const ICON_CAPTURE=requireAsset('../Icons/add_fill0_wght500.png') as Texture
const ICON_PLAN=requireAsset('../Icons/checklist_fill0_wght500.png') as Texture
const ICON_PROFILE=requireAsset('../Icons/person_fill0_wght500.png') as Texture
const ICON_HELP=requireAsset('../Icons/help_fill0_wght500.png') as Texture
function style(t:Text,r:TextRole){t.size=SCALE[r].size;(t as Text&{weight?:number}).weight=SCALE[r].weight;t.depthTest=true;t.horizontalOverflow=HorizontalOverflow.Overflow;t.verticalOverflow=VerticalOverflow.Overflow}

@component
export class FocusOrbitWorkspaceUI extends BaseScriptComponent implements SpatialTaskManipulationHost {
  public onTaskSelected=new Event<string>(); public onMoveFocus=new Event<void>(); public onMoveNext=new Event<void>(); public onMoveWaiting=new Event<void>(); public onMoveLater=new Event<void>();
  public onStartFocus=new Event<void>(); public onPause=new Event<void>(); public onComplete=new Event<void>(); public onClose=new Event<void>(); public onReset=new Event<void>()
  public onExitSession=new Event<void>();public onOpenProfile=new Event<void>();public onOpenPlan=new Event<void>();public onAcceptPlan=new Event<void>()
  public onOpenCapture=new Event<void>();public onCaptureTask=new Event<{title:string;minutes:number;toNext:boolean}>()
  public onRequestClearAll=new Event<void>();public onConfirmClearAll=new Event<void>()
  public onRecoveryAction=new Event<RecoveryAction>()
  public onSpatialDropRequested=new Event<{taskId:string;destination:TaskState}>()
  private cardLabels:Record<string,Text>={};private cardMetaLabels:Record<string,Text>={};private cardRoots:Record<string,SceneObject>={};private cardAccents:Record<string,SceneObject>={};private cardStates:Record<string,TaskState>={};private activeDragId:string|null=null;private detailRoot!:SceneObject; private detailDimmer!:SceneObject;private detailTitle!:Text; private detailMeta!:Text;private detailPrimary!:SceneObject;private detailPrimaryLabel!:Text;private detailSecondary!:SceneObject;private detailSecondaryLabel!:Text;private detailState=TaskState.Inbox
  private sessionRoot!:SceneObject; private sessionTitle!:Text; private timerText!:Text;private sessionMeta!:Text;private sessionPrimary!:SceneObject;private sessionPrimaryLabel!:Text;private sessionSecondary!:SceneObject;private sessionSecondaryLabel!:Text;private sessionMode:'FOCUS'|'RECOVERY'|'BREAK'|'BREAK_DONE'='FOCUS';private sessionTotalMs=1; private messageRoot!:SceneObject; private messageText!:Text; private workspaceRoot!:SceneObject; private focusHeader!:Text;private navRoot!:SceneObject;private headerBackdropRoot!:SceneObject;private workspaceBackdropRoot!:SceneObject;private profileRoot!:SceneObject;private profileBody!:Text;private clearAllRoot!:SceneObject;private planRoot!:SceneObject;private planBody!:Text;private planNote!:Text;private captureRoot!:SceneObject;private captureTitle!:Text;private captureMeta!:Text;private captureMinutes=20;private captureToNext=false;private captureQuickIndex=0
  private getStartedRoot!:SceneObject;private instructionsRoot!:SceneObject;private instructionsStart!:SceneObject;private instructionsBack!:SceneObject;private headerIdentityRoots:SceneObject[]=[];private getStartedIntroRoots:SceneObject[]=[];private onboardingState:OnboardingState='WORKSPACE';private helpMode=false
  private readonly captureQuickTitles=['Send project update','Review tomorrow plan','Prepare meeting notes']
  private budgetText!:Text
  private orbitSlots:SceneObject[]=[]
  private focusCore:SceneObject|null=null;private focusCoreRestScale:vec3|null=null
  private focusCoreGroup:SceneObject|null=null;private focusCoreGroupRestPosition:vec3|null=null
  private waitingEmptyRoot!:SceneObject
  private nextZone!:SceneObject;private focusZone!:SceneObject;private waitingZone!:SceneObject;private inboxZone!:SceneObject
  private spatial!:SpatialTaskManipulationController;private spatialFocusCount=0;private pendingSpatial:{id:string;position:vec3}|null=null
  onAwake(){this.spatial=new SpatialTaskManipulationController(this);this.sceneObject.createComponent('Component.Canvas');this.build()}
  private build(){
    const backdropLayer=this.obj(this.sceneObject,'WorkspaceBackdropLayer',new vec3(0,0,0.6))
    this.headerBackdropRoot=this.decorativePanel(backdropLayer,'HeaderActionBackdrop',new vec3(0,10.5,-0.65),new vec2(49.5,17),0.34)
    this.workspaceBackdropRoot=this.decorativePanel(backdropLayer,'TaskWorkspaceBackdrop',new vec3(0,-13.4,-0.75),new vec2(50.5,25.5),0.22)
    const content=this.obj(this.sceneObject,'Content',new vec3(0,0,0.6))
    const col=this.flex(content,FlexDirection.Column,51,39.5,0.35,0.6)
    this.headerIdentityRoots.push(this.flexChild(col,49,3.35,(o)=>this.text(o,'FOCUS ORBIT','Title2',HorizontalAlignment.Center)))
    this.headerIdentityRoots.push(this.flexChild(col,49,1.9,(o)=>this.text(o,'Put what matters within reach','Body',HorizontalAlignment.Center)))
    this.headerIdentityRoots.push(this.flexChild(col,49,2.2,(o)=>this.budgetText=this.text(o,'ATTENTION BUDGET  ·  0 / 3','Caption',HorizontalAlignment.Center)))
    this.navRoot=this.flexChild(col,45,7.55,(o)=>{const nav=this.flex(o,FlexDirection.Column,45,7.55,0.15,0);const primary=this.flexChild(nav,31,3.7,p=>this.flex(p,FlexDirection.Row,31,3.7,1.4,0));const capture=this.iconAction(primary,'CAPTURE',ICON_CAPTURE,13,()=>this.onOpenCapture.invoke());capture.name='Action-CAPTURE';const plan=this.iconAction(primary,'PLAN',ICON_PLAN,13,()=>this.onOpenPlan.invoke());plan.name='Action-PLAN';const secondary=this.flexChild(nav,35,3.7,s=>this.flex(s,FlexDirection.Row,35,3.7,15,0));const profile=this.iconAction(secondary,'PROFILE',ICON_PROFILE,9,()=>this.onOpenProfile.invoke(),1.55);profile.name='Action-PROFILE';const help=this.iconAction(secondary,'',ICON_HELP,6,()=>this.showInstructions(true),1.75);help.name='Action-?'})
    this.workspaceRoot=this.flexChild(col,49,21,(o)=>this.buildWorkspace(o))
    this.detailDimmer=this.obj(content,'ContextDimmer',new vec3(0,-1,4));this.detailDimmer.enabled=false;const dp=this.detailDimmer.createComponent(BackPlate.getTypeName()) as BackPlate;dp.size=new vec2(47,25);dp.style='simple'
    this.detailRoot=this.obj(content,'TaskContextPanel',new vec3(0,-1,6));this.buildActions(this.detailRoot);this.detailRoot.enabled=false
    const foreground=new vec3(0,-1,6)
    this.sessionRoot=this.obj(content,'FocusCapsule',new vec3(10.5,5.2,6));this.sessionRoot.enabled=false;this.buildSession(this.sessionRoot)
    this.profileRoot=this.obj(content,'FocusProfilePanel',foreground);this.profileRoot.enabled=false;this.buildProfile(this.profileRoot);(this.profileRoot.getComponent(BackPlate.getTypeName()) as BackPlate).style='default'
    this.clearAllRoot=this.obj(content,'ClearAllTasksConfirmation',new vec3(0,-1,7));this.clearAllRoot.enabled=false;this.buildClearAllConfirmation(this.clearAllRoot)
    this.planRoot=this.obj(content,'FocusRecommendationPanel',foreground);this.planRoot.enabled=false;this.buildPlan(this.planRoot);(this.planRoot.getComponent(BackPlate.getTypeName()) as BackPlate).style='default'
    this.captureRoot=this.obj(content,'FocusCapturePanel',foreground);this.captureRoot.enabled=false;this.buildCapture(this.captureRoot);(this.captureRoot.getComponent(BackPlate.getTypeName()) as BackPlate).style='default'
    this.getStartedRoot=this.obj(content,'FocusGetStartedPanel',foreground);this.getStartedRoot.enabled=false;this.buildGetStarted(this.getStartedRoot)
    this.instructionsRoot=this.obj(content,'FocusInstructionsPanel',new vec3(0,1.5,6));this.instructionsRoot.enabled=false;this.buildInstructions(this.instructionsRoot)
    this.messageRoot=this.obj(content,'AttentionBudgetMessage');this.messageRoot.enabled=false;const mp=this.messageRoot.createComponent(BackPlate.getTypeName()) as BackPlate;mp.size=new vec2(29,8);const mt=this.obj(this.messageRoot,'Message',new vec3(0,0,0.7));this.messageText=this.text(mt,'FOCUS ORBIT FULL\nYour attention budget is 3.\nComplete, defer, or replace a task.','Body',HorizontalAlignment.Center)
    this.refreshOnboardingFromStorage()
  }
  private buildWorkspace(parent:SceneObject){const row=this.flex(parent,FlexDirection.Row,49,21,1.6,0.4);this.nextZone=this.zone(row,'NEXT',13);this.focusZone=this.zone(row,'FOCUS  0 / 3',21,true);this.waitingZone=this.zone(row,'WAITING / LATER',13);this.inboxZone=this.obj(parent,'InboxZone',new vec3(0,-5.1,0.8));this.text(this.obj(this.inboxZone,'InboxLabel',new vec3(0,0,0.15)),'INBOX','Caption',HorizontalAlignment.Center)}
  private zone(parent:SceneObject,name:string,w:number,isFocus=false){let result!:SceneObject;this.flexChild(parent,w,20,(zone)=>{result=zone;zone.name='Section-'+name;const z=this.obj(zone,'ZoneContent',new vec3(0,6,0.6));const c=this.flex(z,FlexDirection.Column,w,5,0.45,0.6);this.flexChild(c,w-1.2,2.3,o=>{const label=this.text(o,name,isFocus?'Headline1':'Subheadline',HorizontalAlignment.Center);if(isFocus)this.focusHeader=label});if(name==='WAITING / LATER'){this.waitingEmptyRoot=this.obj(zone,'WaitingEmptyState',new vec3(0,1.2,0.7));this.text(this.waitingEmptyRoot,'Deferred tasks appear here.','Caption',HorizontalAlignment.Center)}});return result}
  public setTasks(tasks:OrbitTask[]){
    if(this.pendingSpatial&&tasks.some(t=>t.id===this.pendingSpatial!.id)&&Object.keys(this.cardRoots).length){this.reconcileSpatialTasks(tasks);return}
    this.spatial.clearCards();for(const k in this.cardRoots)this.cardRoots[k].destroy();this.cardRoots={};this.cardLabels={};this.cardMetaLabels={};this.cardAccents={};this.cardStates={}
    const active=tasks.filter(t=>t.state!==TaskState.Done); const positions:Record<string,vec3>={}
    const buckets:Record<string,OrbitTask[]>={FOCUS:[],NEXT:[],WAITING:[],LATER:[],INBOX:[]};active.forEach(t=>buckets[t.state].push(t));this.focusHeader.text=`FOCUS  ${buckets.FOCUS.length} / 3`
    this.spatialFocusCount=buckets.FOCUS.length;this.budgetText.text=`ATTENTION BUDGET  ·  ${buckets.FOCUS.length} / 3`;this.updateOrbitSlots(buckets.FOCUS.length);this.waitingEmptyRoot.enabled=buckets.WAITING.length+buckets.LATER.length===0
    const focusX=buckets.FOCUS.length===1?[0]:buckets.FOCUS.length===2?[-4.8,4.8]:[-7.5,0,7.5];buckets.FOCUS.forEach((t,i)=>positions[t.id]=new vec3(focusX[i],i===1?2.65:1.7,2.25));buckets.NEXT.forEach((t,i)=>positions[t.id]=new vec3(-18.4,2-i*5.8,1.25));buckets.WAITING.forEach((t,i)=>positions[t.id]=new vec3(18.4,2-i*5.8,0.85));buckets.LATER.forEach((t,i)=>positions[t.id]=new vec3(18.4,2-(buckets.WAITING.length+i)*5.8,0.85));buckets.INBOX.forEach((t,i)=>positions[t.id]=new vec3(-5.2+i*10.4,-8,0.75))
    for(const t of active){const target=positions[t.id];const start=this.pendingSpatial&&this.pendingSpatial.id===t.id?this.pendingSpatial.position:target;const o=this.obj(this.workspaceRoot,'Task-'+t.id,start);this.cardRoots[t.id]=o;this.cardStates[t.id]=t.state;const cardW=t.state===TaskState.Focus?7.1:7;const cardH=4.6;const surface=this.obj(o,'CardSurface',new vec3(0,0,-0.08));const back=surface.createComponent(BackPlate.getTypeName()) as BackPlate;back.size=new vec2(cardW,cardH);back.style=t.state===TaskState.Focus?'default':'simple';back.onInitialized.add(()=>{back.interactable.enabled=false;back.interactionPlane.enabled=false;const collider=surface.getComponent('Physics.ColliderComponent') as ColliderComponent;if(collider)collider.enabled=false});const b=o.createComponent(Button.getTypeName()) as Button;b.size=new vec3(cardW,cardH,1);b.opacity=t.state===TaskState.Focus?1:0.84;const accent=this.obj(o,'FocusAccent',new vec3(0,1.72,0.3));const accentText=this.text(accent,'━━━━━━','Caption',HorizontalAlignment.Center);accentText.size=29;accentText.textFill.color=new vec4(0.26,0.78,1,0.96);accentText.layoutRect=Rect.create(-cardW/2+0.32,cardW/2-0.32,-0.3,0.3);accent.enabled=t.state===TaskState.Focus;this.cardAccents[t.id]=accent;const titleRoot=this.obj(o,'TaskTitle',new vec3(0,0.38,0.18));const txt=this.text(titleRoot,t.title,'Task',HorizontalAlignment.Center);txt.horizontalOverflow=HorizontalOverflow.Wrap;txt.textFill.color=t.state===TaskState.Focus?new vec4(1,1,1,1):new vec4(0.9,0.92,0.94,0.94);txt.layoutRect=Rect.create(-cardW/2+0.48,cardW/2-0.48,-1.15,1.15);this.cardLabels[t.id]=txt;const metaRoot=this.obj(o,'TaskMeta',new vec3(0,-1.42,0.19));const meta=this.text(metaRoot,`${t.estimatedMinutes} MIN`,'Meta',HorizontalAlignment.Center);meta.textFill.color=t.state===TaskState.Focus?new vec4(0.86,0.94,1,0.92):new vec4(0.78,0.82,0.86,0.78);meta.layoutRect=Rect.create(-cardW/2+0.55,cardW/2-0.55,-0.45,0.45);this.cardMetaLabels[t.id]=meta;b.onTriggerUp.add(()=>{if(!this.spatial.shouldSuppressTap(t.id))this.onTaskSelected.invoke(t.id)});o.getTransform().setLocalScale(t.state===TaskState.Focus?new vec3(1.06,1.06,1.06):vec3.one());this.spatial.registerCard(t.id,t.state,o,b,target);if(start!==target)this.animateCard(o,target)}this.pendingSpatial=null
  }
  private reconcileSpatialTasks(tasks:OrbitTask[]){
    const active=tasks.filter(t=>t.state!==TaskState.Done);const buckets:Record<string,OrbitTask[]>={FOCUS:[],NEXT:[],WAITING:[],LATER:[],INBOX:[]};active.forEach(t=>buckets[t.state].push(t));const positions:Record<string,vec3>={}
    this.spatialFocusCount=buckets.FOCUS.length;this.focusHeader.text=`FOCUS  ${buckets.FOCUS.length} / 3`;this.budgetText.text=`ATTENTION BUDGET  ·  ${buckets.FOCUS.length} / 3`;this.updateOrbitSlots(buckets.FOCUS.length);this.waitingEmptyRoot.enabled=buckets.WAITING.length+buckets.LATER.length===0
    const focusX=buckets.FOCUS.length===1?[0]:buckets.FOCUS.length===2?[-4.8,4.8]:[-7.5,0,7.5];buckets.FOCUS.forEach((t,i)=>positions[t.id]=new vec3(focusX[i],i===1?2.65:1.7,2.25));buckets.NEXT.forEach((t,i)=>positions[t.id]=new vec3(-18.4,2-i*5.8,1.25));buckets.WAITING.forEach((t,i)=>positions[t.id]=new vec3(18.4,2-i*5.8,0.85));buckets.LATER.forEach((t,i)=>positions[t.id]=new vec3(18.4,2-(buckets.WAITING.length+i)*5.8,0.85));buckets.INBOX.forEach((t,i)=>positions[t.id]=new vec3(-5.2+i*10.4,-8,0.75))
    for(const t of active){const root=this.cardRoots[t.id];if(!root)continue;this.cardStates[t.id]=t.state;const w=t.state===TaskState.Focus?7.1:7;const surface=root.getChild(0);const back=surface.getComponent(BackPlate.getTypeName()) as BackPlate;back.size=new vec2(w,4.6);back.style=t.state===TaskState.Focus?'default':'simple';const button=root.getComponent(Button.getTypeName()) as Button;button.size=new vec3(w,4.6,1);button.opacity=t.state===TaskState.Focus?1:0.84;const accent=this.cardAccents[t.id];accent.enabled=t.state===TaskState.Focus;const accentText=accent.getComponent('Component.Text') as Text;accentText.layoutRect=Rect.create(-w/2+0.32,w/2-0.32,-0.3,0.3);const label=this.cardLabels[t.id];label.textFill.color=t.state===TaskState.Focus?new vec4(1,1,1,1):new vec4(0.9,0.92,0.94,0.94);label.layoutRect=Rect.create(-w/2+0.48,w/2-0.48,-1.15,1.15);const meta=this.cardMetaLabels[t.id];meta.textFill.color=t.state===TaskState.Focus?new vec4(0.86,0.94,1,0.92):new vec4(0.78,0.82,0.86,0.78);meta.layoutRect=Rect.create(-w/2+0.55,w/2-0.55,-0.45,0.45);root.getTransform().setLocalScale(t.state===TaskState.Focus?new vec3(1.06,1.06,1.06):vec3.one());this.spatial.updateCardState(t.id,t.state,positions[t.id]);this.animateCard(root,positions[t.id])}
    this.pendingSpatial=null;this.previewSpatialDestination(null,true)
  }
  public getSpatialFocusCount(){return this.spatialFocusCount}
  public beginSpatialTaskDrag(taskId:string){this.activeDragId=taskId;this.detailRoot.enabled=false;this.detailDimmer.enabled=false;const accent=this.cardAccents[taskId];if(accent)accent.enabled=true;const root=this.cardRoots[taskId];if(root){const button=root.getComponent(Button.getTypeName()) as Button;button.opacity=1}const label=this.cardLabels[taskId];if(label)label.textFill.color=new vec4(1,1,1,1)}
  public endSpatialTaskDrag(taskId:string){const state=this.cardStates[taskId];const accent=this.cardAccents[taskId];if(accent)accent.enabled=state===TaskState.Focus;const root=this.cardRoots[taskId];if(root){const button=root.getComponent(Button.getTypeName()) as Button;button.opacity=state===TaskState.Focus?1:0.84}const label=this.cardLabels[taskId];if(label)label.textFill.color=state===TaskState.Focus?new vec4(1,1,1,1):new vec4(0.88,0.9,0.92,0.9);if(this.activeDragId===taskId)this.activeDragId=null}
  public previewSpatialDestination(destination:TaskState|null,focusAvailable:boolean){const selected=destination===TaskState.Later?TaskState.Waiting:destination;this.setZoneScale(this.nextZone,selected===TaskState.Next);this.setZoneScale(this.focusZone,selected===TaskState.Focus);this.setZoneScale(this.waitingZone,selected===TaskState.Waiting);this.setZoneScale(this.inboxZone,selected===TaskState.Inbox);this.updateOrbitSlots(this.spatialFocusCount,selected===TaskState.Focus&&focusAvailable?this.spatialFocusCount:-1,selected===TaskState.Focus&&!focusAvailable);this.setFocusCorePreview(selected===TaskState.Focus,focusAvailable)}
  public requestSpatialTaskDrop(taskId:string,destination:TaskState,releasePosition:vec3){this.pendingSpatial={id:taskId,position:releasePosition};this.onSpatialDropRequested.invoke({taskId,destination})}
  public rejectSpatialDrop(taskId:string){this.pendingSpatial=null;this.spatial.rejectActive(taskId)}
  public returnSpatialTaskToHome(root:SceneObject,home:vec3){const target=new vec3(home.x,home.y,home.z);const settle=this.createEvent('DelayedCallbackEvent');settle.bind(()=>this.animateCard(root,target));settle.reset(0.03)}
  private setZoneScale(zone:SceneObject,active:boolean){if(!zone)return;const s=active?1.045:1;zone.getTransform().setLocalScale(new vec3(s,s,s))}
  private animateCard(root:SceneObject,target:vec3){const start=root.getTransform().getLocalPosition();let elapsed=0;const e=this.createEvent('UpdateEvent');e.bind(()=>{elapsed+=getDeltaTime();const p=Math.min(1,elapsed/0.2);const eased=1-Math.pow(1-p,3);root.getTransform().setLocalPosition(vec3.lerp(start,target,eased));if(p>=1){root.getTransform().setLocalPosition(target);e.enabled=false}})}
  private buildActions(parent:SceneObject){const plate=parent.createComponent(BackPlate.getTypeName()) as BackPlate;plate.size=new vec2(35,14);plate.style='dark';const content=this.obj(parent,'ContextContent',new vec3(0,0,0.7));const col=this.flex(content,FlexDirection.Column,35,14,0.8,1);this.flexChild(col,32,4.5,o=>{this.detailTitle=this.text(o,'Select a task','Headline1',HorizontalAlignment.Center);this.detailMeta=this.text(this.obj(o,'Meta',new vec3(0,-2.1,0.15)),'','Caption',HorizontalAlignment.Center)});const row=this.flexChild(col,32,5,o=>this.flex(o,FlexDirection.Row,32,5,1,0));const primary=this.dynamicAction(row,'FOCUS',11,()=>{if(this.detailState===TaskState.Focus)this.onStartFocus.invoke();else this.onMoveFocus.invoke()});this.detailPrimary=primary.root;this.detailPrimaryLabel=primary.label;const secondary=this.dynamicAction(row,'LATER',10,()=>{if(this.detailState===TaskState.Inbox||this.detailState===TaskState.Later||this.detailState===TaskState.Waiting)this.onMoveNext.invoke();else this.onMoveLater.invoke()});this.detailSecondary=secondary.root;this.detailSecondaryLabel=secondary.label;const close=this.action(row,'CLOSE',8,()=>this.onClose.invoke());close.name='Action-×'}
  private buildSession(parent:SceneObject){const p=parent.createComponent(BackPlate.getTypeName()) as BackPlate;p.size=new vec2(27,16);p.style='dark';const c=this.obj(parent,'CapsuleContent',new vec3(0,0,0.7));const col=this.flex(c,FlexDirection.Column,27,16,0.35,0.8);this.flexChild(col,24,2.5,o=>this.sessionMeta=this.text(o,'FOCUS','Subheadline',HorizontalAlignment.Center));this.flexChild(col,24,3.5,o=>{this.sessionTitle=this.text(o,'','Body',HorizontalAlignment.Center);this.sessionTitle.horizontalOverflow=HorizontalOverflow.Wrap});this.flexChild(col,24,2.5,o=>this.timerText=this.text(o,'00:00','Headline1',HorizontalAlignment.Center));const row=this.flexChild(col,24,4,o=>this.flex(o,FlexDirection.Row,24,4,0.8,0));const a=this.dynamicAction(row,'PAUSE',10,()=>this.sessionPrimaryAction());this.sessionPrimary=a.root;this.sessionPrimaryLabel=a.label;const b=this.dynamicAction(row,'COMPLETE',11,()=>this.sessionSecondaryAction());this.sessionSecondary=b.root;this.sessionSecondaryLabel=b.label;this.sessionMeta.size=41;this.sessionMeta.weight=700;this.sessionTitle.size=39;this.sessionTitle.weight=500;this.timerText.size=54;this.timerText.weight=700;this.sessionPrimaryLabel.size=39;this.sessionPrimaryLabel.weight=500;this.sessionSecondaryLabel.size=39;this.sessionSecondaryLabel.weight=500}
  private buildProfile(parent:SceneObject){const p=parent.createComponent(BackPlate.getTypeName()) as BackPlate;p.size=new vec2(39,28);const c=this.obj(parent,'ProfileContent',new vec3(0,0,0.7));const col=this.flex(c,FlexDirection.Column,39,28,0.45,1);this.flexChild(col,36,3.5,o=>this.text(o,'YOUR FOCUS PROFILE','HeadlineXL',HorizontalAlignment.Center));this.flexChild(col,35,12.5,o=>this.profileBody=this.text(o,'LEARNING YOUR FOCUS PATTERN','Body',HorizontalAlignment.Center));const utility=this.flexChild(col,32,3.5,o=>this.flex(o,FlexDirection.Row,32,3.5,0,0));const clear=this.action(utility,'Clear all tasks',16,()=>this.onRequestClearAll.invoke());clear.name='Action-Clear all tasks';const row=this.flexChild(col,34,4.5,o=>this.flex(o,FlexDirection.Row,34,4.5,1,0));this.action(row,'PLAN',10,()=>this.onOpenPlan.invoke());this.action(row,'CLOSE',10,()=>this.closeOverlays())}
  private buildClearAllConfirmation(parent:SceneObject){const p=parent.createComponent(BackPlate.getTypeName()) as BackPlate;p.size=new vec2(37,21);p.style='dark';const c=this.obj(parent,'ClearAllContent',new vec3(0,0,0.7));const col=this.flex(c,FlexDirection.Column,37,21,0.65,1.2);this.flexChild(col,34,3.5,o=>this.text(o,'CLEAR ALL TASKS?','Headline1',HorizontalAlignment.Center));this.flexChild(col,33,8,o=>{const t=this.text(o,'This will remove all tasks from your workspace.\n\nThis cannot be undone.','Body',HorizontalAlignment.Center);t.horizontalOverflow=HorizontalOverflow.Wrap});const row=this.flexChild(col,32,4.5,o=>this.flex(o,FlexDirection.Row,32,4.5,1,0));this.action(row,'CANCEL',11,()=>this.cancelClearAll());const clear=this.action(row,'CLEAR ALL',12,()=>this.onConfirmClearAll.invoke());clear.name='Action-CLEAR ALL'}
  private buildPlan(parent:SceneObject){const p=parent.createComponent(BackPlate.getTypeName()) as BackPlate;p.size=new vec2(41,29);p.style='dark';const c=this.obj(parent,'PlanContent',new vec3(0,0,0.7));const col=this.flex(c,FlexDirection.Column,41,29,0.7,1.1);this.flexChild(col,38,3.5,o=>this.text(o,"TODAY'S FOCUS",'HeadlineXL',HorizontalAlignment.Center));this.flexChild(col,37,14,o=>this.planBody=this.text(o,'Preparing recommendation…','Body',HorizontalAlignment.Center));this.flexChild(col,37,3,o=>this.planNote=this.text(o,'','Caption',HorizontalAlignment.Center));const row=this.flexChild(col,35,5,o=>this.flex(o,FlexDirection.Row,35,5,1,0));this.action(row,'ACCEPT',11,()=>this.onAcceptPlan.invoke());this.action(row,'CLOSE',10,()=>this.closeOverlays())}
  private buildCapture(parent:SceneObject){const p=parent.createComponent(BackPlate.getTypeName()) as BackPlate;p.size=new vec2(41,27);p.style='dark';const c=this.obj(parent,'CaptureContent',new vec3(0,0,0.7));const col=this.flex(c,FlexDirection.Column,41,27,0.65,1.1);this.flexChild(col,38,3,o=>this.text(o,'CAPTURE','HeadlineXL',HorizontalAlignment.Center));this.flexChild(col,37,4,o=>{this.captureTitle=this.text(o,this.captureQuickTitles[0],'Body',HorizontalAlignment.Center);this.captureTitle.horizontalOverflow=HorizontalOverflow.Wrap});this.flexChild(col,37,2.5,o=>this.captureMeta=this.text(o,'20 MIN  •  INBOX','Caption',HorizontalAlignment.Center));const inputRow=this.flexChild(col,37,4,o=>this.flex(o,FlexDirection.Row,37,4,0.8,0));this.action(inputRow,'TYPE TITLE',13,()=>this.openKeyboard());this.action(inputRow,'QUICK TITLE',13,()=>this.nextQuickTitle());const durationRow=this.flexChild(col,37,4,o=>this.flex(o,FlexDirection.Row,37,4,0.8,0));this.action(durationRow,'10 MIN',9,()=>this.setCaptureDuration(10));this.action(durationRow,'20 MIN',9,()=>this.setCaptureDuration(20));this.action(durationRow,'30 MIN',9,()=>this.setCaptureDuration(30));const footer=this.flexChild(col,37,4,o=>this.flex(o,FlexDirection.Row,37,4,0.8,0));this.action(footer,'INBOX / NEXT',14,()=>{this.captureToNext=!this.captureToNext;this.refreshCaptureMeta()});this.action(footer,'ADD',8,()=>this.onCaptureTask.invoke({title:this.captureTitle.text,minutes:this.captureMinutes,toNext:this.captureToNext}));this.action(footer,'CLOSE',8,()=>this.closeOverlays())}
  private buildGetStarted(parent:SceneObject){const p=parent.createComponent(BackPlate.getTypeName()) as BackPlate;p.size=new vec2(39,22);p.style='simple';this.makePlateVisualOnly(parent,p,0.31);const c=this.obj(parent,'GetStartedContent',new vec3(0,0,0.7));const col=this.flex(c,FlexDirection.Column,39,22,0.55,1.2);this.getStartedIntroRoots.push(this.flexChild(col,35,3.4,o=>this.text(o,'FOCUS ORBIT','Title2',HorizontalAlignment.Center)));this.getStartedIntroRoots.push(this.flexChild(col,35,2.5,o=>this.text(o,'Put what matters within reach.','Body',HorizontalAlignment.Center)));const intro=this.flexChild(col,34,5,o=>{const t=this.text(o,'Organize what needs your attention.\nFocus on only three priorities.','Body',HorizontalAlignment.Center);t.textFill.color=new vec4(0.9,0.92,0.94,0.9)});intro.name='OnboardingIntro';this.getStartedIntroRoots.push(intro);const row=this.flexChild(col,24,5,o=>this.flex(o,FlexDirection.Row,24,5,0,0));const button=this.action(row,'GET STARTED',18,()=>this.showInstructions(false));this.getStartedIntroRoots.push(button)}
  private buildInstructions(parent:SceneObject){const p=parent.createComponent(BackPlate.getTypeName()) as BackPlate;p.size=new vec2(43,30);p.style='simple';this.makePlateVisualOnly(parent,p,0.33);const c=this.obj(parent,'InstructionsContent',new vec3(0,0,0.7));const col=this.flex(c,FlexDirection.Column,43,30,0.4,1);this.flexChild(col,39,3.4,o=>this.text(o,'HOW IT WORKS','HeadlineXL',HorizontalAlignment.Center));const steps=this.flexChild(col,39,16.2,o=>{const stack=this.flex(o,FlexDirection.Column,39,16.2,0.3,0);this.onboardingStep(stack,'01','CAPTURE','Add what you need to do.',ICON_CAPTURE);this.onboardingStep(stack,'02','ORGANIZE','Move tasks through your spatial workspace.',ICON_PLAN);this.onboardingStep(stack,'03','FOCUS','Keep only three priorities in your Focus Orbit.',null)});steps.name='OnboardingSteps';this.flexChild(col,38,2.1,o=>{const t=this.text(o,'○   ○   ○     ONLY THREE PRIORITIES','Caption',HorizontalAlignment.Center);t.textFill.color=new vec4(0.65,0.88,1,0.96)});const row=this.flexChild(col,36,4.5,o=>this.flex(o,FlexDirection.Row,36,4.5,0.8,0));this.instructionsStart=this.action(row,'ENTER WORKSPACE',18,()=>this.completeOnboarding());this.instructionsBack=this.action(row,'BACK',10,()=>this.closeHelp())}
  public showGetStarted(){this.helpMode=false;this.onboardingState='GET_STARTED';this.hideAllPresentation();this.setHeaderIdentityVisible(false);this.positionFocusCoreForOnboarding(true);this.getStartedRoot.enabled=true;this.reveal(this.getStartedRoot);this.playGetStartedIntro()}
  public showInstructions(fromHelp:boolean){this.helpMode=fromHelp;this.onboardingState='INSTRUCTIONS';this.hideAllPresentation();this.setHeaderIdentityVisible(false);this.positionFocusCoreForOnboarding(false);this.instructionsRoot.enabled=true;this.instructionsStart.enabled=!fromHelp;this.instructionsBack.enabled=fromHelp;this.reveal(this.instructionsRoot)}
  public completeOnboarding(){global.persistentStorageSystem.store.putBool(ONBOARDING_KEY,true);this.helpMode=false;this.showWorkspace();console.log('[FocusOrbit] OnboardingCompleted')}
  public closeHelp(){if(!this.helpMode)return;this.helpMode=false;this.showWorkspace();console.log('[FocusOrbit] HelpClosed')}
  public refreshOnboardingFromStorage(){const store=global.persistentStorageSystem.store;const done=store.has(ONBOARDING_KEY)&&store.getBool(ONBOARDING_KEY);if(done)this.showWorkspace();else this.showGetStarted()}
  public resetOnboardingForTest(){global.persistentStorageSystem.store.putBool(ONBOARDING_KEY,false);this.showGetStarted()}
  public getOnboardingState(){return this.onboardingState}
  private showWorkspace(){this.onboardingState='WORKSPACE';this.getStartedRoot.enabled=false;this.instructionsRoot.enabled=false;this.positionFocusCoreForOnboarding(false);this.setHeaderIdentityVisible(true);this.headerBackdropRoot.enabled=true;this.workspaceBackdropRoot.enabled=true;this.navRoot.enabled=true;this.workspaceRoot.getTransform().setLocalScale(vec3.one());this.workspaceRoot.enabled=true}
  private hideAllPresentation(){this.headerBackdropRoot.enabled=false;this.workspaceBackdropRoot.enabled=false;this.navRoot.enabled=false;this.workspaceRoot.enabled=false;this.detailRoot.enabled=false;this.detailDimmer.enabled=false;this.sessionRoot.enabled=false;this.profileRoot.enabled=false;this.planRoot.enabled=false;this.captureRoot.enabled=false;this.clearAllRoot.enabled=false;this.getStartedRoot.enabled=false;this.instructionsRoot.enabled=false;this.messageRoot.enabled=false}
  private reveal(root:SceneObject){const tr=root.getTransform();const target=vec3.one();tr.setLocalScale(target.uniformScale(0.96));let elapsed=0;const e=this.createEvent('UpdateEvent');e.bind(()=>{elapsed+=getDeltaTime();const p=Math.min(1,elapsed/0.16);const eased=1-Math.pow(1-p,3);tr.setLocalScale(vec3.lerp(target.uniformScale(0.96),target,eased));if(p>=1){tr.setLocalScale(target);e.enabled=false}})}
  public showDetail(t:OrbitTask|null){this.detailRoot.enabled=!!t;this.detailDimmer.enabled=!!t;if(t){this.detailState=t.state;this.detailTitle.text=t.title;this.detailMeta.text=`${t.state}  •  ${t.estimatedMinutes} MIN`;const focused=t.state===TaskState.Focus;this.detailPrimary.name=focused?'Action-START':'Action-FOCUS';this.detailPrimaryLabel.text=focused?'START FOCUS':'FOCUS';const next=t.state===TaskState.Inbox||t.state===TaskState.Later||t.state===TaskState.Waiting;this.detailSecondary.name=next?'Action-NEXT':'Action-LATER';this.detailSecondaryLabel.text=next?'NEXT':'LATER'}}
  public showSession(t:OrbitTask|null,remainingMs:number,running:boolean){this.headerBackdropRoot.enabled=!t;this.workspaceBackdropRoot.enabled=!t;this.navRoot.enabled=!t;this.workspaceRoot.enabled=!t;this.detailRoot.enabled=false;this.detailDimmer.enabled=false;this.profileRoot.enabled=false;this.planRoot.enabled=false;this.captureRoot.enabled=false;this.getStartedRoot.enabled=false;this.instructionsRoot.enabled=false;this.sessionRoot.enabled=!!t;if(t){this.sessionMode='FOCUS';this.sessionTotalMs=Math.max(1,t.estimatedMinutes*60000);this.sessionTitle.text=t.title;this.sessionSecondary.enabled=true;this.setSessionAction(this.sessionSecondary,this.sessionSecondaryLabel,'COMPLETE');this.updateTimer(remainingMs,running);this.reveal(this.sessionRoot)}}
  public showRecovery(activeMs:number,strong:boolean,totalMs:number){this.hideAllPresentation();this.sessionRoot.enabled=true;this.sessionMode='RECOVERY';this.sessionMeta.text=strong?'2 FOCUS SESSIONS COMPLETE':'SESSION COMPLETE';this.sessionTitle.text=strong?'Take a 2-minute reset?':'Take a moment before your next priority.';this.timerText.text=`${Math.max(1,Math.round((strong?totalMs:activeMs)/60000))} MIN FOCUSED`;this.sessionSecondary.enabled=true;this.setSessionAction(this.sessionPrimary,this.sessionPrimaryLabel,strong?'START BREAK':'BREAK');this.setSessionAction(this.sessionSecondary,this.sessionSecondaryLabel,strong?'NOT NOW':'CONTINUE');this.reveal(this.sessionRoot)}
  public showShortCompletion(activeMs:number){this.hideAllPresentation();this.sessionRoot.enabled=true;this.sessionMode='RECOVERY';this.sessionMeta.text='SESSION COMPLETE';this.sessionTitle.text='Ready when you are.';this.timerText.text=`${Math.max(0,Math.round(activeMs/60000))} MIN FOCUSED`;this.sessionSecondary.enabled=false;this.setSessionAction(this.sessionPrimary,this.sessionPrimaryLabel,'CONTINUE');this.reveal(this.sessionRoot)}
  public showBreak(ms:number){this.hideAllPresentation();this.sessionRoot.enabled=true;this.sessionMode='BREAK';this.sessionMeta.text='RESET';this.sessionTitle.text='Take a short walk  •  stretch  •  hydrate';this.updateBreak(ms);this.sessionSecondary.enabled=false;this.setSessionAction(this.sessionPrimary,this.sessionPrimaryLabel,'END BREAK')}
  public updateBreak(ms:number){const s=Math.ceil(ms/1000);this.timerText.text=`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`}
  public showBreakComplete(){this.sessionMode='BREAK_DONE';this.sessionMeta.text='RESET COMPLETE';this.sessionTitle.text='Ready when you are.';this.timerText.text='';this.sessionSecondary.enabled=false;this.setSessionAction(this.sessionPrimary,this.sessionPrimaryLabel,'CONTINUE')}
  private sessionPrimaryAction(){if(this.sessionMode==='FOCUS')this.onPause.invoke();else if(this.sessionMode==='BREAK')this.onRecoveryAction.invoke('END_BREAK');else if(this.sessionMode==='RECOVERY'&&this.sessionPrimaryLabel.text!=='CONTINUE')this.onRecoveryAction.invoke('START_BREAK');else this.onRecoveryAction.invoke('CONTINUE')}
  private sessionSecondaryAction(){if(this.sessionMode==='FOCUS')this.onComplete.invoke();else this.onRecoveryAction.invoke('CONTINUE')}
  private setSessionAction(root:SceneObject,label:Text,value:string){root.name='Action-'+value;label.text=value}
  public showProfile(p:FocusProfile,persistence:string,switching:string){this.hideBase();this.profileRoot.enabled=true;this.planRoot.enabled=false;this.profileBody.text=p.insufficientData?`LEARNING YOUR FOCUS PATTERN\n\nComplete more Focus Sessions to improve recommendations.\n\nFOCUS PERSISTENCE  ${persistence}\nPLANNING ACCURACY  ${p.planningAccuracy}%\nSWITCHING PATTERN  ${switching}\nBEST FOCUS WINDOW  ${p.preferredFocusMinutes} MIN`:`FOCUS PERSISTENCE  ${persistence}\nPLANNING ACCURACY  ${p.planningAccuracy}%\nSWITCHING PATTERN  ${switching}\nBEST FOCUS WINDOW  ${p.preferredFocusMinutes} MIN\n\nRecommended attention load: ${p.recommendedTaskLoad}`}
  public showPlan(tasks:OrbitTask[],note:string){this.hideBase();this.profileRoot.enabled=false;this.planRoot.enabled=true;this.planBody.text=tasks.map((t,i)=>`${i+1}\n${t.title}\n${t.estimatedMinutes} MIN`).join('\n\n');this.planNote.text=note}
  public showCapture(){this.hideBase();this.profileRoot.enabled=false;this.planRoot.enabled=false;this.captureRoot.enabled=true;this.refreshCaptureMeta()}
  public showCaptureConfirmation(task:OrbitTask){this.captureTitle.text='ADDED TO '+task.state;this.captureMeta.text=`${task.title}  •  ${task.estimatedMinutes} MIN`;const e=this.createEvent('DelayedCallbackEvent');e.bind(()=>{if(this.captureRoot.enabled){this.captureQuickIndex=0;this.captureTitle.text=this.captureQuickTitles[0];this.closeOverlays()}});e.reset(1.15)}
  public showPlanResult(note:string){this.planNote.text=note}
  public showClearAllConfirmation(){this.profileRoot.enabled=false;this.clearAllRoot.enabled=true;this.reveal(this.clearAllRoot)}
  public cancelClearAll(){this.clearAllRoot.enabled=false;this.profileRoot.enabled=true}
  public finishClearAll(){this.clearAllRoot.enabled=false;this.closeOverlays()}
  public closeOverlays(){this.profileRoot.enabled=false;this.planRoot.enabled=false;this.captureRoot.enabled=false;this.clearAllRoot.enabled=false;this.headerBackdropRoot.enabled=true;this.workspaceBackdropRoot.enabled=true;this.navRoot.enabled=true;this.workspaceRoot.enabled=true;this.detailRoot.enabled=false;this.detailDimmer.enabled=false}
  private hideBase(){this.headerBackdropRoot.enabled=false;this.workspaceBackdropRoot.enabled=false;this.navRoot.enabled=false;this.workspaceRoot.enabled=false;this.detailRoot.enabled=false;this.detailDimmer.enabled=false;this.sessionRoot.enabled=false;this.captureRoot.enabled=false;this.clearAllRoot.enabled=false}
  private setCaptureDuration(minutes:number){this.captureMinutes=minutes;this.refreshCaptureMeta()}
  private nextQuickTitle(){this.captureQuickIndex=(this.captureQuickIndex+1)%this.captureQuickTitles.length;this.captureTitle.text=this.captureQuickTitles[this.captureQuickIndex]}
  private refreshCaptureMeta(){this.captureMeta.text=`${this.captureMinutes} MIN  •  ${this.captureToNext?'NEXT':'INBOX'}`}
  private openKeyboard(){const options=new TextInputSystem.KeyboardOptions();options.enablePreview=true;options.keyboardType=TextInputSystem.KeyboardType.Text;options.returnKeyType=TextInputSystem.ReturnKeyType.Done;options.initialText=this.captureTitle.text;options.initialSelectedRange=new vec2(0,options.initialText.length);options.onTextChanged=(value:string)=>{if(value.trim().length)this.captureTitle.text=value.trim()};options.onReturnKeyPressed=()=>global.textInputSystem.dismissKeyboard();options.onKeyboardStateChanged=()=>{};options.onError=(code:number,description:string)=>{console.warn('[FocusOrbit] Keyboard unavailable '+code+': '+description)};global.textInputSystem.requestKeyboard(options)}
  public updateTimer(ms:number,running:boolean){const s=Math.ceil(ms/1000);this.sessionMeta.text=running?'FOCUS':'PAUSED';this.timerText.text=`${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}  •  ${Math.max(0,Math.min(100,Math.round((1-ms/this.sessionTotalMs)*100)))}%`;this.setSessionAction(this.sessionPrimary,this.sessionPrimaryLabel,running?'PAUSE':'RESUME')}
  public showBudgetMessage(){this.messageRoot.enabled=true;const e=this.createEvent('DelayedCallbackEvent');e.bind(()=>this.messageRoot.enabled=false);e.reset(2.8)}
  private updateOrbitSlots(count:number,preview=-1,fullWarning=false){if(!this.orbitSlots.length){const visit=(o:SceneObject)=>{if(o.name.indexOf('Focus Slot ')===0)this.orbitSlots.push(o);if(o.name==='Focus Core'){this.focusCore=o;this.focusCoreRestScale=o.getTransform().getLocalScale()}for(let i=0;i<o.getChildrenCount();i++)visit(o.getChild(i))};for(let i=0;i<global.scene.getRootObjectsCount();i++)visit(global.scene.getRootObject(i));this.orbitSlots.sort((a,b)=>a.name.localeCompare(b.name));if(this.orbitSlots.length>3)this.orbitSlots=this.orbitSlots.slice(0,3)}for(let i=0;i<this.orbitSlots.length;i++){const tr=this.orbitSlots[i].getTransform();const target=i<count?(fullWarning?1.18:1.08):(i===preview?1.4:0.78);tr.setLocalScale(new vec3(target,target,target))}}
  private setFocusCorePreview(active:boolean,available:boolean){if(!this.focusCore||!this.focusCoreRestScale)return;const factor=active?(available?1.045:1.025):1;this.focusCore.getTransform().setLocalScale(this.focusCoreRestScale.uniformScale(factor))}
  private setHeaderIdentityVisible(visible:boolean){for(const root of this.headerIdentityRoots)root.enabled=visible}
  private onboardingStep(parent:SceneObject,num:string,title:string,body:string,icon:Texture|null){const row=this.flexChild(parent,38,5,o=>this.flex(o,FlexDirection.Row,38,5,0.65,0.25));row.name='OnboardingStep-'+title;this.flexChild(row,3.2,4.2,o=>{const t=this.text(o,num,'Caption',HorizontalAlignment.Center);t.textFill.color=new vec4(0.56,0.82,1,0.9)});this.flexChild(row,3.6,4.2,o=>{if(icon){const ec=o.createComponent(ElementContent.getTypeName()) as ElementContent;ec.leadingIcon=icon;ec.leadingIconSize=1.65;ec.sizeOverride=new vec2(3.6,4.2);ec.contentAlignment='center'}else{const t=this.text(o,'○ ○ ○','Meta',HorizontalAlignment.Center);t.textFill.color=new vec4(0.65,0.88,1,0.96)}});this.flexChild(row,29.4,4.4,o=>{const stack=this.flex(o,FlexDirection.Column,29.4,4.4,0.05,0);this.flexChild(stack,28.8,1.8,x=>this.text(x,title,'Subheadline',HorizontalAlignment.Left));this.flexChild(stack,28.8,2.4,x=>{const t=this.text(x,body,'Body',HorizontalAlignment.Left);t.textFill.color=new vec4(0.9,0.92,0.94,0.86)})})}
  private positionFocusCoreForOnboarding(active:boolean){this.updateOrbitSlots(this.spatialFocusCount);if(!this.focusCore)return;if(!this.focusCoreGroup){this.focusCoreGroup=this.focusCore.getParent();if(this.focusCoreGroup){const p=this.focusCoreGroup.getTransform().getLocalPosition();this.focusCoreGroupRestPosition=new vec3(p.x,p.y,p.z)}}if(!this.focusCoreGroup||!this.focusCoreGroupRestPosition)return;const p=this.focusCoreGroupRestPosition;this.focusCoreGroup.getTransform().setLocalPosition(active?new vec3(p.x,p.y-6,p.z):new vec3(p.x,p.y,p.z))}
  private playGetStartedIntro(){for(let i=0;i<this.getStartedIntroRoots.length;i++){const root=this.getStartedIntroRoots[i];root.getTransform().setLocalScale(new vec3(0.94,0.94,0.94));if(i===this.getStartedIntroRoots.length-1)root.enabled=false;const delay=this.createEvent('DelayedCallbackEvent');delay.bind(()=>{root.enabled=true;const tr=root.getTransform();const from=tr.getLocalScale();let elapsed=0;const e=this.createEvent('UpdateEvent');e.bind(()=>{elapsed+=getDeltaTime();const p=Math.min(1,elapsed/0.16);const eased=1-Math.pow(1-p,3);tr.setLocalScale(vec3.lerp(from,vec3.one(),eased));if(p>=1){tr.setLocalScale(vec3.one());e.enabled=false}})});delay.reset(0.08+i*0.12)}}
  private makePlateVisualOnly(root:SceneObject,plate:BackPlate,opacity:number){plate.onInitialized.add(()=>{plate.interactable.destroy();plate.interactionPlane.destroy();const collider=root.getComponent('Physics.ColliderComponent') as ColliderComponent;if(collider)collider.destroy();const visual=root.getComponent(RoundedRectangle.getTypeName()) as RoundedRectangle;if(visual){visual.opacity=opacity;visual.backgroundColor=new vec4(0.58,0.62,0.66,1);visual.border=true;visual.borderSize=0.018;visual.borderColor=new vec4(0.92,0.96,1,0.22)}})}
  private decorativePanel(parent:SceneObject,name:string,pos:vec3,size:vec2,opacity:number){const root=this.obj(parent,name,pos);const plate=root.createComponent(BackPlate.getTypeName()) as BackPlate;plate.size=size;plate.style='simple';plate.onInitialized.add(()=>{plate.interactable.destroy();plate.interactionPlane.destroy();const collider=root.getComponent('Physics.ColliderComponent') as ColliderComponent;if(collider)collider.destroy();const visual=root.getComponent(RoundedRectangle.getTypeName()) as RoundedRectangle;if(visual){visual.opacity=opacity;visual.backgroundColor=new vec4(0.58,0.62,0.66,1);visual.border=true;visual.borderSize=0.018;visual.borderColor=new vec4(0.92,0.96,1,0.24)}});return root}
  private iconAction(parent:SceneObject,label:string,icon:Texture,w:number,fn:()=>void,iconSize=1.65){return this.flexChild(parent,w,4,o=>{o.name='Action-'+(label||'?');const b=o.createComponent(Button.getTypeName()) as Button;b.size=new vec3(w,3.4,1);const content=o.createComponent(ElementContent.getTypeName()) as ElementContent;content.text=label;content.textSize=SCALE.Button.size;content.leadingIcon=icon;content.leadingIconSize=iconSize;content.spacing=0.6;content.contentAlignment='center';content.paddingLeft=0.45;content.paddingRight=0.45;b.onTriggerUp.add(fn)})}
  private action(parent:SceneObject,label:string,w:number,fn:()=>void){return this.flexChild(parent,w,4,o=>{o.name='Action-'+label;const b=o.createComponent(Button.getTypeName()) as Button;b.size=new vec3(w,3.4,1);this.text(this.obj(o,'ButtonLabel',new vec3(0,0,0.1)),label,'Button',HorizontalAlignment.Center);b.onTriggerUp.add(fn)})}
  private dynamicAction(parent:SceneObject,label:string,w:number,fn:()=>void){let text!:Text;const root=this.flexChild(parent,w,4,o=>{o.name='Action-'+label;const b=o.createComponent(Button.getTypeName()) as Button;b.size=new vec3(w,3.4,1);text=this.text(this.obj(o,'ButtonLabel',new vec3(0,0,0.1)),label,'Button',HorizontalAlignment.Center);b.onTriggerUp.add(fn)});return{root,label:text}}
  private text(parent:SceneObject,value:string,role:TextRole,align:HorizontalAlignment):Text{const t=parent.createComponent('Component.Text') as Text;t.text=value;style(t,role);t.horizontalAlignment=align;t.verticalAlignment=VerticalAlignment.Center;t.layoutRect=Rect.create(-0.5,0.5,-0.5,0.5);const i=parent.createComponent(FlexItem.getTypeName()) as FlexItem;i.alignSelf=FlexAlignSelf.Stretch;return t}
  private obj(parent:SceneObject,name:string,pos?:vec3){const o=global.scene.createSceneObject(name);o.setParent(parent);if(pos)o.getTransform().setLocalPosition(pos);return o}
  private flex(parent:SceneObject,d:FlexDirection,w:number,h:number,gap:number,pad:number){const f=parent.createComponent(FlexLayout.getTypeName()) as FlexLayout;f.width=w;f.height=h;f.direction=d;f.alignItems=FlexAlign.Stretch;f.justifyContent=FlexJustify.Center;if(d===FlexDirection.Row)f.columnGap=gap;else f.rowGap=gap;f.paddingTop=pad;f.paddingBottom=pad;f.paddingLeft=pad;f.paddingRight=pad;return parent}
  private flexChild(parent:SceneObject,w:number,h:number,b:(o:SceneObject)=>void){const o=this.obj(parent,'Item');const i=o.createComponent(FlexItem.getTypeName()) as FlexItem;i.overrideWidth=w;i.overrideHeight=h;i.flexShrink=0;b(o);return o}
}
