import {scenariosIndex} from 'Leaf.lspkg/Scenarios/decorator/ScenarioIndexDecorator'
import {ScenarioMetadata} from 'Leaf.lspkg/Scenarios/scenario/ScenarioMetadata'
import {FocusOrbitLaunchScenario} from './FocusOrbitLaunchScenario';import {FocusOrbitEnterFocusScenario} from './FocusOrbitEnterFocusScenario';import {FocusOrbitBudgetScenario} from './FocusOrbitBudgetScenario';import {FocusOrbitOpenTaskScenario} from './FocusOrbitOpenTaskScenario';import {FocusOrbitStartScenario} from './FocusOrbitStartScenario';import {FocusOrbitPauseScenario} from './FocusOrbitPauseScenario';import {FocusOrbitCompleteScenario} from './FocusOrbitCompleteScenario';import {FocusOrbitReachabilityScenario} from './FocusOrbitReachabilityScenario';import {FocusOrbitRestartScenario} from './FocusOrbitRestartScenario'
import {FocusOrbitPhase2MetricsScenario} from './FocusOrbitPhase2MetricsScenario';import {FocusOrbitPhase2ProfileScenario} from './FocusOrbitPhase2ProfileScenario';import {FocusOrbitPhase2DeferScenario} from './FocusOrbitPhase2DeferScenario';import {FocusOrbitPhase2AccuracyScenario} from './FocusOrbitPhase2AccuracyScenario';import {FocusOrbitPhase2WindowScenario} from './FocusOrbitPhase2WindowScenario';import {FocusOrbitPhase2InsufficientScenario} from './FocusOrbitPhase2InsufficientScenario';import {FocusOrbitPhase2RecommendationScenario} from './FocusOrbitPhase2RecommendationScenario';import {FocusOrbitPhase2ProfileUIScenario} from './FocusOrbitPhase2ProfileUIScenario';import {FocusOrbitPhase2PlanUIScenario} from './FocusOrbitPhase2PlanUIScenario';import {FocusOrbitPhase2ConfirmationScenario} from './FocusOrbitPhase2ConfirmationScenario';import {FocusOrbitPhase2BudgetPlanScenario} from './FocusOrbitPhase2BudgetPlanScenario';import {FocusOrbitPhase2DismissScenario} from './FocusOrbitPhase2DismissScenario'
import {FocusOrbitPhase3CaptureUIScenario} from './FocusOrbitPhase3CaptureUIScenario';import {FocusOrbitPhase3CaptureFlowScenario} from './FocusOrbitPhase3CaptureFlowScenario';import {FocusOrbitPhase3CaptureModelScenario} from './FocusOrbitPhase3CaptureModelScenario';import {FocusOrbitPhase3CapturePlanScenario} from './FocusOrbitPhase3CapturePlanScenario'
import {FocusOrbitOnboardingFirstLaunchScenario} from './FocusOrbitOnboardingFirstLaunchScenario';import {FocusOrbitOnboardingFlowScenario} from './FocusOrbitOnboardingFlowScenario';import {FocusOrbitOnboardingHelpScenario} from './FocusOrbitOnboardingHelpScenario';import {FocusOrbitOnboardingReachabilityScenario} from './FocusOrbitOnboardingReachabilityScenario'
import {FocusOrbitSpatialFocusScenario} from './FocusOrbitSpatialFocusScenario';import {FocusOrbitSpatialSecondaryScenario} from './FocusOrbitSpatialSecondaryScenario';import {FocusOrbitSpatialBudgetScenario} from './FocusOrbitSpatialBudgetScenario';import {FocusOrbitSpatialFallbackScenario} from './FocusOrbitSpatialFallbackScenario';import {FocusOrbitSpatialReachabilityScenario} from './FocusOrbitSpatialReachabilityScenario'
@component
export class FocusOrbitLeafIndex extends BaseScriptComponent{
 @scenariosIndex static scenariosIndex:ScenarioMetadata[]=[
  {id:'focus-orbit-launch',typename:FocusOrbitLaunchScenario.getTypeName()},
  {id:'focus-orbit-enter-focus',typename:FocusOrbitEnterFocusScenario.getTypeName()},
  {id:'focus-orbit-attention-budget',typename:FocusOrbitBudgetScenario.getTypeName()},
  {id:'focus-orbit-open-task',typename:FocusOrbitOpenTaskScenario.getTypeName()},
  {id:'focus-orbit-start-focus',typename:FocusOrbitStartScenario.getTypeName()},
  {id:'focus-orbit-pause',typename:FocusOrbitPauseScenario.getTypeName()},
  {id:'focus-orbit-complete',typename:FocusOrbitCompleteScenario.getTypeName()},
  {id:'focus-orbit-reachability',typename:FocusOrbitReachabilityScenario.getTypeName()},
  {id:'focus-orbit-restart',typename:FocusOrbitRestartScenario.getTypeName()},
  {id:'focus-orbit-p2-session-metrics',typename:FocusOrbitPhase2MetricsScenario.getTypeName()},{id:'focus-orbit-p2-profile-update',typename:FocusOrbitPhase2ProfileScenario.getTypeName()},{id:'focus-orbit-p2-defer-switch',typename:FocusOrbitPhase2DeferScenario.getTypeName()},{id:'focus-orbit-p2-planning-accuracy',typename:FocusOrbitPhase2AccuracyScenario.getTypeName()},{id:'focus-orbit-p2-focus-window',typename:FocusOrbitPhase2WindowScenario.getTypeName()},{id:'focus-orbit-p2-insufficient-data',typename:FocusOrbitPhase2InsufficientScenario.getTypeName()},{id:'focus-orbit-p2-recommendation',typename:FocusOrbitPhase2RecommendationScenario.getTypeName()},{id:'focus-orbit-p2-profile-ui',typename:FocusOrbitPhase2ProfileUIScenario.getTypeName()},{id:'focus-orbit-p2-plan-ui',typename:FocusOrbitPhase2PlanUIScenario.getTypeName()},{id:'focus-orbit-p2-confirmation',typename:FocusOrbitPhase2ConfirmationScenario.getTypeName()},{id:'focus-orbit-p2-budget-safe',typename:FocusOrbitPhase2BudgetPlanScenario.getTypeName()},{id:'focus-orbit-p2-dismiss',typename:FocusOrbitPhase2DismissScenario.getTypeName()},
  {id:'focus-orbit-p3-capture-ui',typename:FocusOrbitPhase3CaptureUIScenario.getTypeName()},{id:'focus-orbit-p3-capture-flow',typename:FocusOrbitPhase3CaptureFlowScenario.getTypeName()},{id:'focus-orbit-p3-capture-model',typename:FocusOrbitPhase3CaptureModelScenario.getTypeName()},{id:'focus-orbit-p3-capture-plan',typename:FocusOrbitPhase3CapturePlanScenario.getTypeName()},
  {id:'focus-orbit-onboarding-first-launch',typename:FocusOrbitOnboardingFirstLaunchScenario.getTypeName()},{id:'focus-orbit-onboarding-flow',typename:FocusOrbitOnboardingFlowScenario.getTypeName()},{id:'focus-orbit-onboarding-help',typename:FocusOrbitOnboardingHelpScenario.getTypeName()},{id:'focus-orbit-onboarding-reachability',typename:FocusOrbitOnboardingReachabilityScenario.getTypeName()},
  {id:'focus-orbit-spatial-focus',typename:FocusOrbitSpatialFocusScenario.getTypeName()},{id:'focus-orbit-spatial-secondary',typename:FocusOrbitSpatialSecondaryScenario.getTypeName()},{id:'focus-orbit-spatial-budget',typename:FocusOrbitSpatialBudgetScenario.getTypeName()},{id:'focus-orbit-spatial-fallback',typename:FocusOrbitSpatialFallbackScenario.getTypeName()},{id:'focus-orbit-spatial-reachability',typename:FocusOrbitSpatialReachabilityScenario.getTypeName()},
 ]
}
