import {FocusOrbitModel,TaskState} from './FocusOrbitModel'
import {FocusOrbitWorkspaceUI} from './FocusOrbitWorkspaceUI'
import {FocusMetricsTracker,FocusProfileManager,PlanningEngine} from './FocusOrbitAdaptive'
import {FocusRecoveryController} from './FocusRecoveryController'

const SFX_SELECT=requireAsset('../GeneratedSFX/TaskSelect.wav') as AudioTrackAsset
const SFX_ACCEPT=requireAsset('../GeneratedSFX/FocusAccept.wav') as AudioTrackAsset
const SFX_DEFER=requireAsset('../GeneratedSFX/TaskDefer.wav') as AudioTrackAsset
const SFX_START=requireAsset('../GeneratedSFX/FocusStart.wav') as AudioTrackAsset
const SFX_PAUSE=requireAsset('../GeneratedSFX/FocusPause.wav') as AudioTrackAsset
const SFX_COMPLETE=requireAsset('../GeneratedSFX/TaskComplete.wav') as AudioTrackAsset
const SFX_FULL=requireAsset('../GeneratedSFX/BudgetExceeded.wav') as AudioTrackAsset
const SFX_CAPTURE=requireAsset('../GeneratedSFX/CaptureConfirm.wav') as AudioTrackAsset

@component
export class FocusOrbitMain extends BaseScriptComponent {
 @input ui!:FocusOrbitWorkspaceUI
 @input core!:SceneObject
 @input completionVfx!:SceneObject
 private model=new FocusOrbitModel();private metrics=new FocusMetricsTracker();private profiles=new FocusProfileManager();private planner=new PlanningEngine();private recovery=new FocusRecoveryController();private recommended:string[]=[];private audio!:AudioComponent;private update!:SceneEvent;private breakRunning=false;private recoveryOffered=false
 onAwake(){this.audio=this.sceneObject.createComponent('Component.AudioComponent') as AudioComponent;this.createEvent('OnStartEvent').bind(()=>this.start())}
 private start(){this.ui.setTasks(this.model.tasks);this.ui.onTaskSelected.add(id=>{const t=this.model.select(id);this.play(SFX_SELECT);this.ui.showDetail(t)});this.ui.onMoveFocus.add(()=>this.move(TaskState.Focus));this.ui.onMoveNext.add(()=>this.move(TaskState.Next));this.ui.onMoveWaiting.add(()=>this.move(TaskState.Waiting));this.ui.onMoveLater.add(()=>this.move(TaskState.Later));this.ui.onSpatialDropRequested.add(drop=>{this.model.select(drop.taskId);const result=this.move(drop.destination,true);if(result!=='ok')this.ui.rejectSpatialDrop(drop.taskId)});this.ui.onStartFocus.add(()=>this.beginFocus());this.ui.onPause.add(()=>this.togglePause());this.ui.onComplete.add(()=>this.complete());this.ui.onExitSession.add(()=>this.exitSession());this.ui.onOpenProfile.add(()=>this.openProfile());this.ui.onOpenPlan.add(()=>this.openPlan());this.ui.onAcceptPlan.add(()=>this.acceptPlan());this.ui.onOpenCapture.add(()=>this.ui.showCapture());this.ui.onCaptureTask.add(data=>this.capture(data.title,data.minutes,data.toNext));this.ui.onRequestClearAll.add(()=>this.requestClearAll());this.ui.onConfirmClearAll.add(()=>this.clearAllTasks());this.ui.onRecoveryAction.add(action=>this.recoveryAction(action));this.ui.onClose.add(()=>this.ui.showDetail(null));this.ui.onReset.add(()=>{this.model.reset();this.metrics.reset();this.ui.closeOverlays();this.ui.setTasks(this.model.tasks)});this.update=this.createEvent('UpdateEvent');this.update.bind(()=>this.tick());this.update.enabled=false;console.log('[FocusOrbit] Ready. Attention budget='+FocusOrbitModel.MAX_FOCUS)}
 private move(state:TaskState,spatial=false):'ok'|'full'|'none'{const result=this.model.moveSelected(state);if(result==='full'){this.play(SFX_FULL);this.pulseCore(1.12,0.18);this.ui.showBudgetMessage();console.log('[FocusOrbit] AttentionBudgetExceeded count='+this.model.focusCount+' input='+(spatial?'spatial':'context'));return result}if(result==='ok'){this.play(state===TaskState.Focus?SFX_ACCEPT:SFX_DEFER);this.pulseCore(1.08,0.2);if(spatial){const settle=this.createEvent('DelayedCallbackEvent');settle.bind(()=>this.ui.setTasks(this.model.tasks));settle.reset(0.06)}else{this.ui.setTasks(this.model.tasks);this.ui.showDetail(this.model.selected)}console.log('[FocusOrbit] TaskMoved '+this.model.selectedId+' destination='+state+' input='+(spatial?'spatial':'context'))}return result}
 private beginFocus(){if(!this.model.start())return;this.metrics.start(this.model.active!);this.play(SFX_START);this.pulseCore(1.18,0.28);this.ui.showSession(this.model.active,this.model.sessionRemainingMs,true);this.update.enabled=true;console.log('[FocusOrbit] FocusStarted '+this.model.active!.id)}
 private togglePause(){const running=this.model.pause();if(running)this.metrics.resume();else this.metrics.pause();this.play(SFX_PAUSE);this.ui.updateTimer(this.model.sessionRemainingMs,this.model.sessionRunning);console.log('[FocusOrbit] Focus'+(running?'Resumed':'Paused'))}
 private tick(){const delta=getDeltaTime()*1000;if(this.breakRunning){const left=this.recovery.tick(delta);this.ui.updateBreak(left);if(left<=0){this.breakRunning=false;this.update.enabled=false;this.recovery.endBreak();this.play(SFX_CAPTURE);this.ui.showBreakComplete()}return}this.model.tick(delta);this.ui.updateTimer(this.model.sessionRemainingMs,this.model.sessionRunning)}
 private complete(){const t=this.model.active;if(!t)return;this.update.enabled=false;const metric=this.metrics.complete();this.play(SFX_COMPLETE);this.runCompletionVfx();this.pulseCore(1.28,0.45);const cardName='Task-'+t.id;this.model.complete();this.ui.setTasks(this.model.tasks);const activeMs=metric?.activeFocusTimeMs||0;const decision=this.recovery.recordCompleted(activeMs);this.recoveryOffered=decision.meaningful;if(decision.meaningful)this.ui.showRecovery(activeMs,decision.strong,decision.recentAccumulatedFocusMs);else this.ui.showShortCompletion(activeMs);console.log('[FocusOrbit] TaskCompleted '+cardName+' focusCount='+this.model.focusCount+' activeMs='+activeMs+' recovery='+(decision.meaningful?(decision.strong?'strong':'optional'):'brief'))}
 private recoveryAction(action:string){if(action==='START_BREAK'){this.recovery.startBreak(Date.now());this.recoveryOffered=false;this.breakRunning=true;this.play(SFX_DEFER);this.ui.showBreak(this.recovery.remainingMs);this.update.enabled=true;console.log('[FocusOrbit] BreakStarted durationMs='+this.recovery.currentBreakDurationMs);return}if(action==='END_BREAK'){this.recovery.endBreak();this.breakRunning=false;this.update.enabled=false;this.play(SFX_PAUSE);this.restoreWorkspace();console.log('[FocusOrbit] BreakEndedEarly');return}if(this.recoveryOffered)this.recovery.skip();this.recoveryOffered=false;this.restoreWorkspace();console.log('[FocusOrbit] RecoveryDismissed')}
 private restoreWorkspace(){this.ui.showSession(null,0,false);this.ui.setTasks(this.model.tasks)}
 private exitSession(){const t=this.model.active;if(!t)return;this.update.enabled=false;const metric=this.metrics.defer();this.model.exitActive();this.play(SFX_DEFER);this.ui.showSession(null,0,false);this.ui.setTasks(this.model.tasks);console.log('[FocusOrbit] FocusExited '+t.id+' activeMs='+(metric?.activeFocusTimeMs||0))}
 private profile(){return this.profiles.calculate(this.metrics.sessions)}
 private openProfile(){const p=this.profile();this.ui.showProfile(p,this.profiles.persistenceLabel(p),this.profiles.switchingLabel(p));console.log('[FocusOrbit] ProfileOpened samples='+p.sampleCount)}
 private openPlan(){const p=this.profile();const tasks=this.planner.recommend(this.model.tasks,p);this.recommended=tasks.map(t=>t.id);this.ui.showPlan(tasks,this.planner.explain(p,tasks));console.log('[FocusOrbit] RecommendationGenerated '+this.recommended.join(','))}
 private acceptPlan(){const available=FocusOrbitModel.MAX_FOCUS-this.model.focusCount;if(available<=0){this.ui.showPlanResult('FOCUS ORBIT FULL — free a slot before accepting.');return}let moved=0;const old=this.model.selectedId;for(const id of this.recommended){const task=this.model.tasks.find(t=>t.id===id);if(!task||task.state===TaskState.Focus||moved>=available)continue;this.model.select(id);if(this.model.moveSelected(TaskState.Focus)==='ok')moved++}if(old)this.model.select(old);this.ui.setTasks(this.model.tasks);this.ui.showPlanResult(moved?`Accepted ${moved} task${moved===1?'':'s'} into available Focus slots.`:'Current Focus already matches this plan.');console.log('[FocusOrbit] RecommendationAccepted moved='+moved+' focusCount='+this.model.focusCount)}
 private capture(title:string,minutes:number,toNext:boolean){const task=this.model.createTask(title,minutes,toNext?TaskState.Next:TaskState.Inbox);if(!task)return;this.play(SFX_CAPTURE);this.ui.setTasks(this.model.tasks);this.ui.showCaptureConfirmation(task);console.log('[FocusOrbit] TaskCaptured '+task.id+' state='+task.state+' minutes='+task.estimatedMinutes)}
 private requestClearAll(){if(this.model.active){console.log('[FocusOrbit] ClearAllBlocked activeSession='+this.model.active.id);return}this.ui.showClearAllConfirmation()}
 private clearAllTasks(){if(!this.model.clearAllTasks()){console.log('[FocusOrbit] ClearAllBlocked activeSession');return}this.recommended=[];this.ui.setTasks(this.model.tasks);this.ui.finishClearAll();console.log('[FocusOrbit] AllTasksCleared focusCount='+this.model.focusCount)}
 public getTaskCountForTest(){return this.model.tasks.length}
 public getFocusCountForTest(){return this.model.focusCount}
 public isFocusSessionActiveForTest(){return this.model.active!==null}
 private play(track:AudioTrackAsset){this.audio.audioTrack=track;this.audio.play(1)}
 private pulseCore(scale:number,duration:number){if(!this.core)return;const tr=this.core.getTransform();const start=tr.getLocalScale();const peak=start.uniformScale(scale);let time=0;const ev=this.createEvent('UpdateEvent');ev.bind(()=>{time+=getDeltaTime();const p=Math.min(1,time/duration);const wave=Math.sin(p*Math.PI);tr.setLocalScale(vec3.lerp(start,peak,wave));if(p>=1){tr.setLocalScale(start);ev.enabled=false}})}
 private runCompletionVfx(){if(!this.completionVfx)return;this.completionVfx.enabled=true;const count=this.completionVfx.getChildrenCount();for(let i=0;i<count;i++){const c=this.completionVfx.getChild(i);const a=(i/count)*Math.PI*2;c.getTransform().setLocalPosition(new vec3(Math.cos(a)*7,Math.sin(a)*5,0))}let time=0;const ev=this.createEvent('UpdateEvent');ev.bind(()=>{time+=getDeltaTime();const p=Math.min(1,time/0.65);for(let i=0;i<count;i++){const tr=this.completionVfx.getChild(i).getTransform();const start=tr.getLocalPosition();tr.setLocalPosition(vec3.lerp(start,vec3.zero(),0.18+p*0.35));tr.setLocalScale(new vec3(1-p,1-p,1-p))}if(p>=1){this.completionVfx.enabled=false;for(let i=0;i<count;i++)this.completionVfx.getChild(i).getTransform().setLocalScale(vec3.one());ev.enabled=false}})}
}
